###############################################################################
#
# Makefile for a script (e.g. Python), project 6
#
# Students:
# Idan Yamin, ID 205787211, idan.yamin@cs.huji.ac.il
# Mor Moshe, ID 206120537, mor.moshe@cs.huji.ac.il
#
###############################################################################


all:
	chmod a+x Assembler
